export const SYMPTOMS_LIST = [
  "Itchy Eyes",
  "Visual Aura",
  "Runny Nose",
  "Headache",
  "Watery Eyes",
  "Sneezing",
  "Chest Pain",
  "Painful Urination",
  "Pelvic Pain",
  "Severe Headache",
  "Light Sensitivity",
  "Cloudy Urine",
  "Abdominal Pain",
  "Vomiting",
  "Fever",
  "Dizziness",
  "Cold Hands",
  "Cough",
  "Slow Healing",
  "Cold Intolerance",
  "Blurred Vision",
  "Diarrhea",
  "Weight Gain",
  "Nausea",
  "Excessive Thirst",
  "Nasal Congestion",
  "Frequent Urination",
  "Dry Skin",
  "Pale Skin",
  "Fatigue",
  "Constipation",
  "Sore Throat",
  "Shortness Of Breath",
];

export const INITIAL_FORM = {
  weightKg: "",
  heightCm: "",
  severityScore: "",
  systolicBp: "",
  diastolicBp: "",
  temperatureCelsius: "",
  heartRateBpm: "",
  symptomDurationDays: "",
  selectedSymptoms: [],
};

export const FORM_FIELDS = [
  {
    key: "weightKg",
    label: "Weight (kg)",
    labelKey: "aiConsultation.form.fields.weightKg",
    step: "0.1",
    min: "0",
  },
  {
    key: "heightCm",
    label: "Height (cm)",
    labelKey: "aiConsultation.form.fields.heightCm",
    step: "0.1",
    min: "0",
  },
  {
    key: "severityScore",
    label: "Severity Score (0-10)", // 1 => normal, 5 => medium, 10 => urgent
    labelKey: "aiConsultation.form.fields.severityScore",
    step: "1",
    min: "0",
    max: "10",
  },
  {
    key: "systolicBp",
    label: "Systolic BP",
    labelKey: "aiConsultation.form.fields.systolicBp",
    step: "1",
    min: "0",
  },
  {
    key: "diastolicBp",
    label: "Diastolic BP",
    labelKey: "aiConsultation.form.fields.diastolicBp",
    step: "1",
    min: "0",
  },
  {
    key: "temperatureCelsius",
    label: "Temperature (C)",
    labelKey: "aiConsultation.form.fields.temperatureCelsius",
    step: "0.1",
    min: "0",
  },
  {
    key: "heartRateBpm",
    label: "Heart Rate (BPM)",
    labelKey: "aiConsultation.form.fields.heartRateBpm",
    step: "1",
    min: "0",
  },
  {
    key: "symptomDurationDays",
    label: "Symptom Duration (Days)",
    labelKey: "aiConsultation.form.fields.symptomDurationDays",
    step: "1",
    min: "0",
  },
];
