import { FaHeart, FaStar } from "react-icons/fa";
import { motion } from "motion/react";
import { useNavigate } from "react-router-dom";

const HERO_THEMES = [
  {
    bg: "#1a2e1a",
    orb: "rgba(100,160,60,0.22)",
    accentText: "#a8d878",
    accentBg: "rgba(130,200,80,0.12)",
    accentBorder: "rgba(130,200,80,0.25)",
  },
];

const itemVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { type: "spring", stiffness: 300, damping: 24 },
  },
};

function RecipeCard({
  id,
  recipeId,
  title,
  description,
  herbs,
  targetedDiseases,
  createdByAI,
  createdDate,
  averageRating,
  price,
}) {
  const navigate = useNavigate();
  const theme = HERO_THEMES[0];

  return (
    <motion.button
      variants={itemVariants}
      whileHover={{ y: -6 }}
      type="button"
      onClick={() => navigate(`/patient/home/recipes/${id || recipeId}`)}
      className="group flex flex-col overflow-hidden rounded-[20px] border border-black/8 bg-[#faf9f6] text-left h-full w-full transition-shadow duration-300 hover:shadow-2xl"
    >
      {/* Hero */}
      <div
        className="relative flex min-h-4 flex-col justify-between overflow-hidden p-6 "
        style={{ background: theme.bg }}
      >
        {/* Ambient orb */}
        <div
          className="absolute -right-5 -bottom-8 w-32.5 h-32.5 rounded-full pointer-events-none"
          style={{
            background: `radial-gradient(circle, ${theme.orb}, transparent 70%)`,
          }}
        />
        {/* Leaf decoration */}
        <svg
          className="absolute top-4 right-14 opacity-[0.07] pointer-events-none"
          width="60"
          height="80"
          viewBox="0 0 60 80"
          fill="none"
        >
          <path d="M30 2 C50 20 55 50 30 78 C5 50 10 20 30 2Z" fill="#a0d060" />
          <line
            x1="30"
            y1="2"
            x2="30"
            y2="78"
            stroke="#a0d060"
            strokeWidth="1.5"
          />
        </svg>

        {/* Top row */}
        <div className="relative z-10 flex items-start justify-between">
          <span
            className="rounded-full px-3 py-1 text-[10px] font-medium uppercase tracking-[0.15em] border"
            style={{
              color: "rgba(200,230,180,0.65)",
              borderColor: "rgba(150,200,100,0.25)",
              background: "rgba(255,255,255,0.04)",
            }}
          >
            {createdDate || "Recent"}
          </span>
          <span className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-white/6 text-white/40 text-sm transition-colors hover:bg-red-500/20 hover:text-red-400 cursor-pointer">
            <FaHeart />
          </span>
        </div>

        {/* Bottom */}
        <div className="relative z-10 mt-5">
          {createdByAI && (
            <div
              className="mb-2.5 inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[9px] font-medium uppercase tracking-[0.18em] border"
              style={{
                color: theme.accentText,
                background: theme.accentBg,
                borderColor: theme.accentBorder,
              }}
            >
              <span
                className="w-1.5 h-1.5 rounded-full"
                style={{ background: theme.accentText }}
              />
              Generated by AI
            </div>
          )}
          <h3
            className="text-[22px] leading-tight tracking-[-0.01em] transition-colors"
            style={{
              fontWeight: 600,
              color: "#f0ece4",
            }}
          >
            {title}
          </h3>
        </div>
      </div>

      {/* Body */}
      <div className="flex flex-1 flex-col p-5 bg-[#faf9f6]">
        <p className="mb-4 line-clamp-2 text-[12.5px] leading-relaxed text-[#6b7a62]">
          {description}
        </p>

        <div className="mb-4 flex flex-wrap gap-1.5">
          {herbs?.length ? (
            <>
              {herbs.slice(0, 3).map((herb) => (
                <span
                  key={`${herb.herbId}-${herb.herbName}`}
                  className="rounded-full border border-[rgba(70,130,50,0.18)] bg-[#edf5e6] px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em] text-[#3d6634]"
                >
                  {herb.herbName}
                </span>
              ))}
              {herbs.length > 3 && (
                <span className="rounded-full border border-black/[0.07] bg-[#f1f0ec] px-2.5 py-1 text-[10px] font-medium text-[#9aaa90]">
                  +{herbs.length - 3}
                </span>
              )}
            </>
          ) : (
            <span className="rounded-full border border-black/[0.07] bg-[#f1f0ec] px-2.5 py-1 text-[10px] font-medium text-[#9aaa90]">
              Custom Blend
            </span>
          )}
        </div>

        {/* Divider */}
        <div
          className="mb-4 h-px"
          style={{
            background:
              "linear-gradient(to right, transparent, rgba(80,120,60,0.15), transparent)",
          }}
        />

        {/* Footer */}
        <div className="mt-auto flex items-end justify-between gap-3">
          <div className="min-w-0">
            <p className="mb-1 text-[9px] font-medium uppercase tracking-[0.18em] text-[#b0b8a8]">
              Targets
            </p>
            <p className="truncate text-xs font-medium text-[#3a4a34]">
              {targetedDiseases?.length
                ? targetedDiseases.map((d) => d.diseaseName).join(", ")
                : "General Wellness"}
            </p>
          </div>
          <div className="flex shrink-0 gap-1.5">
            <span
              className="flex items-center rounded-full px-2.5 py-1 text-[11px] font-medium"
              style={{ background: theme.bg, color: theme.accentText }}
            >
              {price ? `$${Number(price).toFixed(2)}` : "Free"}
            </span>
            <span className="flex items-center gap-1 rounded-full border border-[rgba(180,140,20,0.18)] bg-[#fef9ec] px-2.5 py-1 text-[11px] font-medium text-[#8a6a10]">
              <FaStar className="text-[#d4a820] text-[10px]" />
              {averageRating != null ? Number(averageRating).toFixed(1) : "New"}
            </span>
          </div>
        </div>
      </div>
    </motion.button>
  );
}

export default RecipeCard;
